use_frameworks!

platform :ios, '10.0'

target 'apptracking_Example' do
  pod 'apptracking', :path => '../'

  target 'apptracking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
